/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/lament-final-opt.glb -t -r public
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three'
import { useFrame } from '@react-three/fiber'
import { useSpring, animated } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Face1: THREE.Mesh
    Face3: THREE.Mesh
    Face4: THREE.Mesh
    Face5: THREE.Mesh
    Face6: THREE.Mesh
    Face2: THREE.Mesh
  }
  materials: {
    wood272k: THREE.MeshStandardMaterial
    brass4k: THREE.MeshStandardMaterial
  }
}

export default function LamentTS(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/lament-final-opt.glb') as GLTFResult

  const cube = useRef<Group>(null!)
  const [active, setActive] = useState(true)

  useFrame((state, delta) => {
    active ? cube.current.rotation.y += delta * 0.2 : cube.current.rotation.y += 0
  })

  const handleRotation = (event: any) => {
    event.stopPropagation()
    setActive(!active)
  }

  // const { scale } = useSpring({ scale: active ? 1.5 : 1 })
  
  return ( 
    <animated.group {...props} dispose={null} onClick={handleRotation} ref={cube}>
      <mesh name='Cube' castShadow geometry={nodes.Cube.geometry} material={materials.wood272k} position={[0, 1.01, 0]} />
      <mesh name='Face1' castShadow geometry={nodes.Face1.geometry} material={materials.brass4k} position={[0.01, 2.01, 0]} scale={[18.65, 7.06, 18.66]} />
      <mesh name='Face2' castShadow geometry={nodes.Face3.geometry} material={materials.brass4k} position={[-1, 1.01, -0.03]} rotation={[0, 0, -Math.PI / 2]} scale={[18.7, 0.19, 18.66]} />
      <mesh name='Face3' castShadow geometry={nodes.Face4.geometry} material={materials.brass4k} position={[0, 1.02, 1]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[18.65, 0.16, 18.65]} />
      <mesh name='Face4' castShadow geometry={nodes.Face5.geometry} material={materials.brass4k} position={[1, 1.02, -0.03]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[18.65, 0.15, 18.66]} />
      <mesh name='Face5' castShadow geometry={nodes.Face6.geometry} material={materials.brass4k} position={[-0.02, 1.02, -1]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[18.65, 0.12, 18.66]} />
      <mesh name='Face6' castShadow geometry={nodes.Face2.geometry} material={materials.brass4k} position={[0.01, 0.01, 0]} scale={[18.65, 7.06, 18.66]} />
    </animated.group>
  )
}

useGLTF.preload('/lament-final-opt.glb')
