/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function LamentConfig(props : any) {
  const { nodes, materials }: any = useGLTF("./lament-final-nom-opt.glb");
  
  const metalTexture = useTexture({
    map: './textures/metal/Metal042A_4K_Color.jpg',
    displacementMap: './textures/metal/Metal042A_4K_Displacement.jpg',
    normalMap: './textures/metal/Metal042A_4K_NormalGL.jpg',
    roughnessMap: './textures/metal/Metal042A_4K_Roughness.jpg',
    metalnessMap: './textures/metal/Metal042A_4K_Metalness.jpg'
  })

  const woodTexture = useTexture({
    map: './textures/wood/Wood027_2K_Color.jpg',
    displacementMap: './textures/wood/Wood027_2K_Displacement.jpg',
    normalMap: './textures/wood/Wood027_2K_NormalGL.jpg',
    roughnessMap: './textures/wood/Wood027_2K_Roughness.jpg',
  })
  
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 1.01, 0]}
      >
        <meshStandardMaterial {...woodTexture} displacementScale={0.00001}/>
      </mesh>
      <mesh
        name="Face3"
        castShadow
        receiveShadow
        geometry={nodes.Face3.geometry}
        material={nodes.Face3.material}
        position={[-1, 1.01, -0.03]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[18.7, 0.19, 18.66]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
        />
      </mesh>
      <mesh
        name="Face5"
        castShadow
        receiveShadow
        geometry={nodes.Face5.geometry}
        material={nodes.Face5.material}
        position={[1, 1.02, -0.03]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[18.65, 0.15, 18.66]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
        />
      </mesh>
      <mesh
        name="Face4"
        castShadow
        receiveShadow
        geometry={nodes.Face4.geometry}
        material={nodes.Face4.material}
        position={[0, 1.02, 1]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[18.65, 0.16, 18.65]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
        />
      </mesh>
      <mesh
        name="Face6"
        castShadow
        receiveShadow
        geometry={nodes.Face6.geometry}
        material={nodes.Face6.material}
        position={[-0.02, 1.02, -1]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[18.65, 0.12, 18.66]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
        />
      </mesh>
      <mesh
        name="Face1"
        castShadow
        receiveShadow
        geometry={nodes.Face1.geometry}
        material={nodes.Face1.material}
        position={[0.01, 2.01, 0]}
        scale={[18.65, 7.06, 18.66]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
          metalness={0.02}
        />
      </mesh>
      <mesh
        name="Face2"
        castShadow
        receiveShadow
        geometry={nodes.Face2.geometry}
        material={nodes.Face2.material}
        position={[0.01, 0.01, 0]}
        scale={[18.65, 7.06, 18.66]}
      >
        <meshStandardMaterial 
          {...metalTexture}
          displacementScale={0.00001}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./lament-final-nom-opt.glb");
