/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/lament-final-nom-opt.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0, 1.01, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face3.geometry}
        // material={nodes.Face3.material}
        position={[-1, 1.01, -0.03]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[18.7, 0.19, 18.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face5.geometry}
        material={nodes.Face5.material}
        position={[1, 1.02, -0.03]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[18.65, 0.15, 18.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face4.geometry}
        material={nodes.Face4.material}
        position={[0, 1.02, 1]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[18.65, 0.16, 18.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face6.geometry}
        material={nodes.Face6.material}
        position={[-0.02, 1.02, -1]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[18.65, 0.12, 18.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face1.geometry}
        material={nodes.Face1.material}
        position={[0.01, 2.02, 0]}
        scale={[18.65, 7.06, 18.66]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Face2.geometry}
        material={nodes.Face2.material}
        position={[0.01, 0.01, 0]}
        scale={[18.65, 7.06, 18.66]}
      />
    </group>
  );
}

useGLTF.preload("/lament-final-nom-opt.glb");